apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana-simple-fp.fullname" . }}
  labels: {{ include "grafana-simple-fp.labels" . | nindent 4 }}
spec:
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    {{- with .Values.deploymentStrategy.rollingUpdate }}
    rollingUpdate: {{ toYaml . | nindent 6 }}
    {{- end }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{ include "grafana-simple-fp.selectorLabels" . | nindent 6 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "grafana-simple-fp.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "grafana-simple-fp.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --mode
            - cluster
            - --watch
            {{- range $key, $value := .Values.alertGroupLabels }}
            - --label-selector
            - {{ $key }}={{ $value }}
            {{- end }}
            {{- range $key, $value := .Values.alertGroupTargetLabels }}
            - --target-labels
            - {{ $key }}={{ $value }}
            {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value }}
            {{- end }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.securityContext }}
          securityContext: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.lifecycle }}
          lifecycle: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts: {{ . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range . }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              {{- include "grafana-simple-fp.selectorLabels" $ | nindent 14 }}
              {{- with ((.labelSelector).matchLabels) }} # workaround full optional nested keys
              {{- tpl (toYaml .) $ | nindent 14 }}
              {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.schedulerName }}
      schedulerName: {{ toYaml . }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      volumes: {{ . | nindent 8 }}
      {{- end }}
